blm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blm import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^chris/', include('chris.urls', namespace='chris')),
    url(r'^sprout/', include('sprout.urls', namespace='sprout')),
]

chris/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^index/$', login, {'template_name': 'chris/index.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page': '../'}, name="logout"),
    url(r'^register/$', views.register, name='register'),
    # url(r'^link_bank/$', views.link_bank, name="bank"),
    url(r'^menu/$', views.menu, name="menu"),
    url(r'^settings/$', views.settings, name="settings"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^reset_password/$', password_reset,{'template_name':
    'chris/reset_password.html', 'post_reset_redirect':
    'chris:password_reset_done', 'email_template_name':
    'chris/reset_password_email.html'}, name="reset_password"), # See tutorial 31

    url(r'^password_reset/done/$', password_reset_done, {'template_name':
    'chris/reset_password_done.html'}, name="password_reset_done"),

    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':
    'chris/reset_password_confirm.html', 'post_reset_redirect':
    'chris:password_reset_complete'}, name="password_reset_confirm"),

    url(r'^password_reset/complete/$', password_reset_complete, {'template_name':
    'chris/reset_password_complete.html'}, name="password_reset_complete")
]

chris/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import date

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    email = models.CharField(max_length=32, default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class Budget(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=30, default='') # name of budget
    amount = models.IntegerField(default=0) # total amount to be set aside
    mode = models.NullBooleanField() # all at once or multiple disbursements
    interval = models.IntegerField(default=0) # days between disbursements
    frequency = models.IntegerField(default=0) # days(1), weeks(2), months(3), 30 days(4), year(5)
    freq_factor = models.IntegerField(default=0) # frequency factor or constant
    pay_value = models.IntegerField(default=0) # amount to be paid at individual disbursement
    pay_qty = models.IntegerField(default=0) # qty of individual disbursements
    pay_count = models.IntegerField(default=0) # count of last disbursement
    next_date = models.DateField(blank=False, null=False) # date of next disbursement to be made
    final_date = models.DateField(null=False, blank=True) # date of last disbursement
    budget_status = models.IntegerField(default=0) # 0=unpaid, 1=paid, 2=disbursement started, 3=disbursement complete, 4=other
    pay_ref = models.CharField(max_length=30, null=True) # Payment reference for funding a budget
    pay_status = models.CharField(max_length=10, null=True) # Status of payment attempt
    amount_funded = models.IntegerField(null=True) # amount funded for budget
    recipient = models.ForeignKey("Bank", blank=True, null=True) # actual account/destination budget is spent on
    recipient_code = models.CharField(max_length=20, blank=False) # required by Paystack
    created = models.DateTimeField(null=False)
    updated = models.DateTimeField(null=False)

class Bank(models.Model):
    holder_name = models.CharField(max_length=55, default="") # The account holder's name
    bank = models.CharField(max_length=55, default="") # The name of the bank
    bank_code = models.IntegerField(blank=True)
    acc_no = models.IntegerField(blank=True) # The recipient (bank) account number
    created = models.DateTimeField(null=False)
    recipient_code = models.CharField(max_length=20, blank=False) # required by Paystack
    user = models.ForeignKey(User)

class Token(models.Model):
    token = models.IntegerField(default=0)
    last_4 = models.CharField(max_length=4, default='0000')

chris/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# The fields in this form are not in the model
# See tutorial 16 Max Goodridge Django tutorials
#
# class RegistrationForm(UserCreationForm):
#     email = forms.EmailField(required=True)
#
#     class Meta:
#         model = User
#         fields = {
#             'username',
#             'first_name',
#             'last_name',
#             'email',
#             'password1',
#             'password2'
#         }
#
#     def save(self, commit=True):
#         user = suer(RegistrationForm, self).save(commit=False)
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.email = self.cleaned_data['email']
#
#         if commit:
#             user.save()
#
#         return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "password",
        )

chris/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from chris.forms import EditProfileForm # RegistrationForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# import json

def login_redirect(request):
    # first two optoins don't work on their own. Should you always
    # use redirect with render?
    # return reverse("login")
    # return reverse("chris:login")
    return redirect(reverse("chris:login"))

def index(request):
    return reverse("login")

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("sprout:home"))
    else:
        form = UserCreationForm()

        context = {'form': form}
        return render(request, 'chris/register.html', context)

# This registers using a custom reg form - also commented out in forms
# See tutorial 16 Max Goodridge Django tutorials
#
# def register(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/chris/home')
#     else:
#         form = RegistrationForm()
#
#         context = {'form': form}
#         return render(request, 'chris/register.html', context)

# Moved to new app
# def home(request):
#     return render(request, 'chris/home.html')

def menu(request):
    return render(request, 'chris/menu.html')

def profile(request):
    context = {
        "user": request.user
    }
    return render(request, 'chris/profile.html', context)

def settings(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse("chris:profile"))
    else:
        form = EditProfileForm(instance=request.user)
        context = {
            "form": form
        }
        return render(request, 'chris/settings.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse("chris:profile"))
        else:
            return redirect(reverse("chris:change_password"))
    else:
        form = PasswordChangeForm(user=request.user)
        context = {
            "form": form
        }
        return render(request, 'chris/change_password.html', context)

chris/templates/chris/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Change Password</title>
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>
{% endblock %}

chris/templates/chris/index.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div id="index">
  <div class="identity">
    <h1>Bare Necessities</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Log In</button>
    </form>
    <input type="text" name="" value="" placeholder="Email address">
    <input type="password" name="" value="" placeholder="Password">
    <p class="forgot">
      <a href="{% url 'chris:reset_password' %}">Forgot Password?</a>
    </p>
    <button type="submit">Log In</button>
    <p><a href="{% url 'chris:register' %}">Don't have an account? Register</a></p>
  </div>
</div>
{% endblock %}

chris/templates/chris/menu.html
{% extends 'base.html' %}

{% block head %}
<title>Menu</title>
{% endblock %}

{% block body %}
<div class="modal">
  This is the modal
</div>
<div id="menu">
  <p>Budgets</p>
  <p>Verified cards</p>
  <p>Linked accounts</p>
  <p>Settings</p>
  <p>Logout</p>
</div>
<section v-show="budgets" class="fence">
  <div id="title-block">
    <h2>All budgets</h2>
    <div class="level-radio">
      <div class=""></div>
      <div id="level">
        <label id="radio" class="one">
          <input type="radio" name="disbursement" value="">
          <span id="level-checkmark" class="checkmark"></span>
        </label>
        <label id="radio" class="two">
          <input type="radio" name="disbursement" value="">
          <span id="level-checkmark" class="checkmark"></span>
        </label>
      </div>
      <div class=""></div>
    </div>
  </div>
  <progress-bar></progress-bar>
  <div id="main">
    <div class="gap">
    </div>
    <div class="q-block">
      <label class="bank">
        Plumbing <span>(Ended December 24, 2018)</span>
        <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Transport <span>(Ended January 02, 2019)</span>
        <p class="acc-name">&#8358; 1,000 | 20 of 20</p>
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Pocket Money <span>(every two weeks | Thursday)</span>
        <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Transport <span>(daily)</span>
        <p class="acc-name">&#8358; 1,000 | 13 of 20</p>
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Internet <span>(July 19, 2019)</span>
        <p class="acc-name">&#8358; 19,800</p>
      </label>
    </div>
  </div>
</section>
<section v-show="linkedBanks" class="fence">
  <div id="title-block">
    <h2>What bank account do you want to receive disbursement?</h2>
  </div>
  <progress-bar></progress-bar>
  <div id="main">
    <div class="gap">
    </div>
    <div class="q-block">
      <label class="bank">
        <p class="acc-name">Adefirst Olafinal</p>
        0011223344 GTBank
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        <p class="acc-name">Adesecond Olathird</p>
        0011223344 Heritage Bank
      </label>
    </div>
    <div class="q-block">
      <label>
        <span class="add-bank">+ Add new account</span>
      </label>
    </div>
    <div class="q-block">
      <label>
        <span class="add-bank">+ Bill</span>
      </label>
    </div>
  </div>
</section>
{% endblock %}

This part is outside the block
  <button>Menu</button>
  <button>modal</button>
  <section v-show="menu === 'linkBank'" class="fence">
    <div id="title-block">
      <h2>Link a bank account to receive disbursements</h2>
    </div>
    <progress-bar></progress-bar>
    <div id="main">
      <div class="gap">
      </div>
      <div class="q-block">
        <label>Select bank
          <option value="">Bank</option>
        </label>
      </div>
      <div class="q-block">
        <label>Enter account number
          <input type="" name="" value="">
        </label>
        <p class="validation">validation</p>
      </div>
    </div>
  </section>
  <section v-show="menu === 'linkedBanks'" class="fence">
    <div id="title-block">
      <h2>What bank account do you want to receive disbursement?</h2>
    </div>
    <progress-bar></progress-bar>
    <div id="main">
      <div class="gap">
      </div>
      <div class="q-block">
        <label class="bank">
          <p class="acc-name">Adefirst Olafinal</p>
          0011223344 GTBank
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          <p class="acc-name">Adesecond Olathird</p>
          0011223344 Heritage Bank
        </label>
      </div>
      <div class="q-block">
        <label>
          <span class="add-bank">+ Add new account</span>
        </label>
      </div>
      <div class="q-block">
        <label>
          <span class="add-bank">+ Bill</span>
        </label>
      </div>
    </div>
  </section>
  <section v-show="menu === 'verifiedCards'" class="fence">
    <div id="title-block"></div>
    <progress-bar></progress-bar>
    <div id="main">
      <div class="gap">
      </div>
      <div class="q-block">
      </div>
      <div class="q-block">
      </div>
    </div>
  </section>
  <section v-show="menu === 'allBudgets'" class="fence">
    <div id="title-block">
      <h2>All budgets</h2>
      <div class="level-radio">
        <div class=""></div>
        <div id="level">
          <label id="radio" class="one">
            <input type="radio" name="disbursement" value="">
            <span id="level-checkmark" class="checkmark"></span>
          </label>
          <label id="radio" class="two">
            <input type="radio" name="disbursement" value="">
            <span id="level-checkmark" class="checkmark"></span>
          </label>
        </div>
        <div class=""></div>
      </div>
    </div>
    <progress-bar></progress-bar>
    <div id="main">
      <div class="gap">
      </div>
      <div class="q-block">
        <label class="bank">
          Plumbing <span>(Ended December 24, 2018)</span>
          <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Transport <span>(Ended January 02, 2019)</span>
          <p class="acc-name">&#8358; 1,000 | 20 of 20</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Pocket Money <span>(every two weeks | Thursday)</span>
          <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Transport <span>(daily)</span>
          <p class="acc-name">&#8358; 1,000 | 13 of 20</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Internet <span>(July 19, 2019)</span>
          <p class="acc-name">&#8358; 19,800</p>
        </label>
      </div>
    </div>
  </section>
  <section v-show="menu === 'activeBudgets'" class="fence">
    <div id="title-block">
      <h2>Active budgets</h2>
      <div class="level-radio">
        <div class=""></div>
        <div id="level">
          <label id="radio" class="one">
            <input type="radio" name="disbursement" value="">
            <span id="level-checkmark" class="checkmark"></span>
          </label>
          <label id="radio" class="two">
            <input type="radio" name="disbursement" value="">
            <span id="level-checkmark" class="checkmark"></span>
          </label>
        </div>
        <div class=""></div>
      </div>
    </div>
    <progress-bar></progress-bar>
    <div id="main">
      <div class="gap">
      </div>
      <div class="q-block">
        <label class="bank">
          Pocket Money <span>(every two weeks | Thursday)</span>
          <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Transport <span>(daily)</span>
          <p class="acc-name">&#8358; 1,000 | 13 of 20</p>
        </label>
      </div>
      <div class="q-block">
        <label class="bank">
          Internet <span>(July 19, 2019)</span>
          <p class="acc-name">&#8358; 19,800</p>
        </label>
      </div>
    </div>
  </section>

chris/templates/chris/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<p>{{user}}</p>
<p>{{user.first_name}}</p>
<p>{{user.last_name}}</p>
<p>{{user.email}}</p>
{% endblock %}

chris/templates/chris/register.html
{% extends 'base.html' %}

{% block head %}
<title>Signup</title>
{% endblock %}

{% block body %}
<div id="index">
  <div class="identity">
    <h1>Bare Necessities</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign Up</button>
    </form>
    <input type="text" name="" value="" placeholder="Email address">
    <input type="password" name="" value="" placeholder="Password">
    <p class="forgot">Forgot password?</p>
    <button type="submit">Log In</button>
    <p>Don't have an account?</p>
  </div>
</div>
{% endblock %}

chris/templates/chris/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset Password</title>
{% endblock %}

{% block body %}
<p>Forgotten your password? Enter your email address below,
   and we'll email instructions for setting a new one.</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Reset password</button>
</form>
{% endblock %}

chris/templates/chris/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset complete</title>
{% endblock %}

{% block body %}
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
<a href="{% url "chris:login" %}">Login</a>
{% endblock %}

chris/templates/chris/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
<title>Enter new password</title>
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Reset password</button>
</form>
{% endblock %}

chris/templates/chris/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset sent</title>
{% endblock %}

{% block body %}
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock %}

chris/templates/chris/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'chris:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

chris/templates/chris/settings.html
{% extends 'base.html' %}

{% block head %}
<title>settings</title>
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>
<section class="fence">
  <div id="title-block">
    <h2>Settings</h2>
  </div>
  <div id="main">
    <div class="gap">
    </div>
    <div class="q-block">
      <label class="bank">
        Password
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Password
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Pocket Money <span>(every two weeks | Thursday)</span>
        <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
      </label>
    </div>
  </div>
</section>
{% endblock %}